datastax/simulacron

common/src/main/java/com/datastax/oss/simulacron/common/cluster/ActivityLog.java

[#17] Use ConcurrentLinkedQueue for ActivityLog.queryLog

---

common/src/main/java/com/datastax/oss/simulacron/common/stubbing/PeerMetadataHandler.java
common/src/test/java/com/datastax/oss/simulacron/common/stubbing/PeerMetadataHandlerTest.java

[#25] Add host_id to system.local metadata

---

common/src/main/java/com/datastax/oss/simulacron/common/cluster/QueryLog.java
http-server/src/main/resources/webroot/swagger/swagger.yaml
http-server/src/test/java/com/datastax/oss/simulacron/http/server/ActivityLogIntegrationTest.java

Fix https://github.com/datastax/simulacron/issues/28

Feature querylog client timestamp

---

pom.xml

[#29] Upgrade jackson-databind to 2.9.2

---

pom.xml

[#33] Upgrade to jackson-databind 2.9.3

---

common/src/main/java/com/datastax/oss/simulacron/common/cluster/ClusterSpec.java
driver-3x/src/test/java/com/datastax/oss/simulacron/driver/Driver3xIntegrationTest.java
http-server/src/main/java/com/datastax/oss/simulacron/http/server/EndpointManager.java
http-server/src/test/java/com/datastax/oss/simulacron/http/server/EndpointIntegrationTest.java
http-server/src/test/java/com/datastax/oss/simulacron/http/server/HttpContainerIntegrationTest.java
http-server/src/test/java/com/datastax/oss/simulacron/http/server/HttpTestUtil.java
native-server/src/main/java/com/datastax/oss/simulacron/server/FrameDecoder.java
native-server/src/test/java/com/datastax/oss/simulacron/server/BoundNodeTest.java
native-server/src/test/java/com/datastax/oss/simulacron/server/TestFrameDecoder.java

Also changes default numTokens to 1 per node (instead of 0).

[#41]  Return protocol error when less than protocol v3 is used

---

common/src/main/java/com/datastax/oss/simulacron/common/result/AlreadyExistsResult.java
common/src/main/java/com/datastax/oss/simulacron/common/stubbing/PrimeDsl.java
http-server/src/main/resources/webroot/swagger/swagger.yaml
http-server/src/test/java/com/datastax/oss/simulacron/http/server/ErrorResultIntegrationTest.java

[#40] Make 'table' optional for 'already_exists' result

---

common/src/main/java/com/datastax/oss/simulacron/common/result/UnavailableResult.java

[#39] Unavailable result should not require message attribute

---

doc/java_api/README.md

Replace com.datastax.simulacron to com.datastax.oss.simulacron

Fix package names in README

---

common/pom.xml
driver-3x/pom.xml
http-server/pom.xml
native-protocol-json/pom.xml
native-server/pom.xml
pom.xml

[#54] OSGi support

---

native-server/src/test/java/com/datastax/oss/simulacron/server/ServerTest.java
pom.xml

[#50] Update jackson-databind dependency to 2.9.5

---

native-protocol-json/src/test/java/com/datastax/oss/simulacron/protocol/json/FrameSerializerTest.java
pom.xml

[#57] Update native-protocol dependency to 1.4.3

---

common/src/main/java/com/datastax/oss/simulacron/common/stubbing/EmptyReturnMetadataHandler.java
native-server/src/main/java/com/datastax/oss/simulacron/server/Server.java

* Querying system_virtual_schema.* should return a Result rather than a VoidResult
* Minor improvement in  the EmptyReturnMetadataHandler class to makes the query matching case insensitive.

system_virtual_tables support

---

native-server/src/main/java/com/datastax/oss/simulacron/server/ByteBufCodec.java

ByteBufCodec.readBytes was returning the underlying buffer if it was a
DirectByteBuf, this inappropriately caused data from subsequent requests
to update data from previous requests.
Most notably, when viewing query log, you could see positional values
from prior queries be corrupted by those from subsequent queries.
To fix this, I simply copied the implementation from
the java drivers' ByteBufPrimitiveCodec.
Fixes #74.

[#74] Fix readBytes so it gets a copy of Buffer instead of direct

---

native-server/src/main/java/com/datastax/oss/simulacron/server/ByteBufCodec.java
pom.xml

[#79] Upgrade to native-protocol 1.4.4

---

.travis.yml

Travis: Use openjdk8

---

native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java

These are my initial thoughts on some additional logs that could be useful. Let me know your thoughts on the format and if there are any more we can add.

Additional logging on prime mismatches (fixes #102)

---

native-server/src/main/java/com/datastax/oss/simulacron/server/Server.java
native-server/src/test/java/com/datastax/oss/simulacron/server/ServerTest.java

Add option to Server Builder to add custom StubMappings to default StubStore (fixes #100)

---

common/src/main/java/com/datastax/oss/simulacron/common/request/Query.java
common/src/test/java/com/datastax/oss/simulacron/common/request/QueryTest.java

Fix plus updated tests with additional coverage

fixes query consistency level match for execute message (issue #115)

---

http-server/src/main/resources/webroot/swagger/index.html

Clearly tell browser to load script in utf-8

#118 Specify charset to utf-8 in script tag
